server:
  port: 8113

spring:
  application:
    name: notification-query-service

  data:
    mongodb:
      uri: mongodb://burak:burak@mongo:27017/notification-system

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: notification-query-group

topics:
  notification-events: notification-events
